name: Nuitka Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "test*"  # for testing
      - "v*"  # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.5.1]
        # os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    # runs-on: ubuntu-latest

    steps:
      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      # maybe not necessary
      - name: Install dependencies
        run: poetry install

      # https://github.com/marketplace/actions/build-executables-or-extension-modules-from-python-projects#usage-details
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          # script-name: hello_world.py
          script-name: qwen7b-tr.py
          onefile: true

      # Uploads artifact
      - name: Upload Artifact
        run: "echo \" \""
        uses: actions/upload-artifact@v3
        with:
          name: exe
          # path: build/hello_world.exe
          path: build/qwen7b-tr.exe
